### ISSUE TITLE
Android Studio Iguana support

### ISSUE THREAD

**Issue by ColtonIdle** [WonJoongLee/BuildFinishNotifier#2]
I'm using Android Studio nightlies (since theyre now published [here](https://developer.android.com/studio/nightly)) but this plugin doesn't work (a lot of my other ones do work though) maybe we can be less restrictive about version support?

**Comment by ColtonIdle** [comment]
canary 1 is now avail and this plugin doesn't work 😭

**Comment by WonJoongLee** [comment]
@ColtonIdle @Renefritze Apologies for the delayed response. 

By updating to the latest version 1.0.3, it's available to use the plugin without any issues. You can view the update notes from [this link](https://github.com/WonJoongLee/BuildFinishNotifier/releases/tag/1.0.3). Thank you always for using the plugin.

**Comment by ColtonIdle** [comment]
Thank you for creating the plugin! I cannot live without it!
