### ISSUE TITLE
Does not work with Jellyfish (2023.3.x)

### ISSUE THREAD

**Issue by jjerome00** [WonJoongLee/BuildFinishNotifier#4]
Plugin is not compatible on newer versions of Android Studio.

**Comment by WonJoongLee** [comment]
@jjerome00 Thank you for reporting the issue! I am currently working on it and will provide an update within this week. I will notify you when the update is available. Thank you once again for your report.

**Comment by WonJoongLee** [comment]
@jjerome00 @renefritze Thank you for waiting! The new version [1.0.4](https://github.com/WonJoongLee/BuildFinishNotifier/releases/tag/1.0.4) now supports the latest version of Android Studio. It has passed the IntelliJ review and is available for download now.

Please tell me if there are any issues.

**Comment by ColtonIdle** [comment]
Thank you @WonJoongLee !!!
